-- ============================================================
-- 博客管理系统 (BMS) - 文章版本历史表
-- 版本: v2.0.0
-- 日期: 2026-03-25
-- 说明: 支持文章版本保存、对比、回滚
-- ============================================================

DROP TABLE IF EXISTS `BMS_ARTICLE_VERSION`;
CREATE TABLE `BMS_ARTICLE_VERSION` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `ARTICLE_ID` VARCHAR(32) NOT NULL COMMENT '文章ID',
    `VERSION_NUMBER` INT NOT NULL COMMENT '版本号',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '文章标题快照',
    `CONTENT` LONGTEXT COMMENT '文章内容快照',
    `SUMMARY` VARCHAR(500) DEFAULT NULL COMMENT '文章摘要快照',
    `CHANGE_SUMMARY` VARCHAR(500) DEFAULT NULL COMMENT '变更摘要',
    `STATUS` VARCHAR(20) DEFAULT 'ACTIVE' COMMENT '状态 (ACTIVE-活跃, ARCHIVED-已归档)',
    `DELETE_FLAG` VARCHAR(255) DEFAULT 'NOT_DELETE' COMMENT '删除标志',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '创建人ID',
    PRIMARY KEY (`ID`),
    INDEX `IDX_VERSION_ARTICLE` (`ARTICLE_ID`),
    INDEX `IDX_VERSION_NUMBER` (`ARTICLE_ID`, `VERSION_NUMBER`),
    UNIQUE KEY `UK_ARTICLE_VERSION` (`ARTICLE_ID`, `VERSION_NUMBER`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文章版本历史表';