-- ============================================================
-- 博客管理系统 (BMS) 数据库初始化脚本
-- 版本: v1.0.0
-- 日期: 2026-03-24
-- 说明: 包含文章、分类、标签、评论、媒体等核心表
-- ============================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ============================================================
-- 1. 文章分类表 (BMS_CATEGORY)
-- ============================================================
DROP TABLE IF EXISTS `BMS_CATEGORY`;
CREATE TABLE `BMS_CATEGORY` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `PARENT_ID` VARCHAR(32) DEFAULT '0' COMMENT '父分类ID',
    `NAME` VARCHAR(50) NOT NULL COMMENT '分类名称',
    `CODE` VARCHAR(50) DEFAULT NULL COMMENT '分类编码',
    `DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '分类描述',
    `ICON` VARCHAR(100) DEFAULT NULL COMMENT '分类图标',
    `SORT_CODE` INT DEFAULT 0 COMMENT '排序码',
    `STATUS` VARCHAR(20) DEFAULT 'ENABLE' COMMENT '状态 (ENABLE-启用, DISABLED-禁用)',
    `EXT_JSON` TEXT DEFAULT NULL COMMENT '扩展信息JSON',
    `DELETE_FLAG` VARCHAR(255) DEFAULT 'NOT_DELETE' COMMENT '删除标志 (NOT_DELETE-未删除, DELETED-已删除)',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '创建人ID',
    `UPDATE_TIME` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新人ID',
    PRIMARY KEY (`ID`),
    INDEX `IDX_CATEGORY_PARENT` (`PARENT_ID`),
    INDEX `IDX_CATEGORY_STATUS` (`STATUS`),
    UNIQUE KEY `UK_CATEGORY_CODE` (`CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文章分类表';

-- ============================================================
-- 2. 文章标签表 (BMS_TAG)
-- ============================================================
DROP TABLE IF EXISTS `BMS_TAG`;
CREATE TABLE `BMS_TAG` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `NAME` VARCHAR(50) NOT NULL COMMENT '标签名称',
    `CODE` VARCHAR(50) DEFAULT NULL COMMENT '标签编码',
    `COLOR` VARCHAR(20) DEFAULT NULL COMMENT '标签颜色',
    `DESCRIPTION` VARCHAR(255) DEFAULT NULL COMMENT '标签描述',
    `SORT_CODE` INT DEFAULT 0 COMMENT '排序码',
    `STATUS` VARCHAR(20) DEFAULT 'ENABLE' COMMENT '状态 (ENABLE-启用, DISABLED-禁用)',
    `EXT_JSON` TEXT DEFAULT NULL COMMENT '扩展信息JSON',
    `DELETE_FLAG` VARCHAR(255) DEFAULT 'NOT_DELETE' COMMENT '删除标志 (NOT_DELETE-未删除, DELETED-已删除)',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '创建人ID',
    `UPDATE_TIME` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新人ID',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_TAG_CODE` (`CODE`),
    INDEX `IDX_TAG_STATUS` (`STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文章标签表';

-- ============================================================
-- 3. 文章表 (BMS_ARTICLE)
-- ============================================================
DROP TABLE IF EXISTS `BMS_ARTICLE`;
CREATE TABLE `BMS_ARTICLE` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `TITLE` VARCHAR(200) NOT NULL COMMENT '文章标题',
    `SUMMARY` VARCHAR(500) DEFAULT NULL COMMENT '文章摘要',
    `CONTENT` LONGTEXT COMMENT '文章内容',
    `COVER_IMAGE` VARCHAR(255) DEFAULT NULL COMMENT '封面图片URL',
    `CATEGORY_ID` VARCHAR(32) NOT NULL COMMENT '分类ID',
    `AUTHOR_ID` VARCHAR(32) NOT NULL COMMENT '作者ID',
    `STATUS` VARCHAR(20) DEFAULT 'DRAFT' COMMENT '状态 (DRAFT-草稿, PUBLISHED-已发布)',
    `VIEW_COUNT` INT DEFAULT 0 COMMENT '阅读量',
    `LIKE_COUNT` INT DEFAULT 0 COMMENT '点赞数',
    `COMMENT_COUNT` INT DEFAULT 0 COMMENT '评论数',
    `IS_TOP` TINYINT DEFAULT 0 COMMENT '是否置顶 (0-否, 1-是)',
    `IS_RECOMMEND` TINYINT DEFAULT 0 COMMENT '是否推荐 (0-否, 1-是)',
    `ALLOW_COMMENT` TINYINT DEFAULT 1 COMMENT '允许评论 (0-否, 1-是)',
    `PUBLISH_TIME` DATETIME DEFAULT NULL COMMENT '发布时间',
    `SEO_KEYWORDS` VARCHAR(255) DEFAULT NULL COMMENT 'SEO关键词',
    `SEO_DESCRIPTION` VARCHAR(500) DEFAULT NULL COMMENT 'SEO描述',
    `SORT_CODE` INT DEFAULT 0 COMMENT '排序码',
    `EXT_JSON` TEXT DEFAULT NULL COMMENT '扩展信息JSON',
    `DELETE_FLAG` VARCHAR(255) DEFAULT 'NOT_DELETE' COMMENT '删除标志 (NOT_DELETE-未删除, DELETED-已删除)',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '创建人ID',
    `UPDATE_TIME` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新人ID',
    PRIMARY KEY (`ID`),
    INDEX `IDX_ARTICLE_CATEGORY` (`CATEGORY_ID`),
    INDEX `IDX_ARTICLE_AUTHOR` (`AUTHOR_ID`),
    INDEX `IDX_ARTICLE_STATUS` (`STATUS`),
    INDEX `IDX_ARTICLE_PUBLISH_TIME` (`PUBLISH_TIME`),
    INDEX `IDX_ARTICLE_TOP` (`IS_TOP`, `PUBLISH_TIME`),
    INDEX `IDX_ARTICLE_RECOMMEND` (`IS_RECOMMEND`, `PUBLISH_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文章表';

-- ============================================================
-- 4. 文章标签关联表 (BMS_ARTICLE_TAG)
-- ============================================================
DROP TABLE IF EXISTS `BMS_ARTICLE_TAG`;
CREATE TABLE `BMS_ARTICLE_TAG` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `ARTICLE_ID` VARCHAR(32) NOT NULL COMMENT '文章ID',
    `TAG_ID` VARCHAR(32) NOT NULL COMMENT '标签ID',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_ARTICLE_TAG` (`ARTICLE_ID`, `TAG_ID`),
    INDEX `IDX_ARTICLE_TAG_ARTICLE` (`ARTICLE_ID`),
    INDEX `IDX_ARTICLE_TAG_TAG` (`TAG_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='文章标签关联表';

-- ============================================================
-- 5. 评论表 (BMS_COMMENT)
-- ============================================================
DROP TABLE IF EXISTS `BMS_COMMENT`;
CREATE TABLE `BMS_COMMENT` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `ARTICLE_ID` VARCHAR(32) NOT NULL COMMENT '文章ID',
    `PARENT_ID` VARCHAR(32) DEFAULT '0' COMMENT '父评论ID (0为顶级评论)',
    `REPLY_USER_ID` VARCHAR(32) DEFAULT NULL COMMENT '回复用户ID',
    `REPLY_USER_NAME` VARCHAR(50) DEFAULT NULL COMMENT '回复用户昵称',
    `NICKNAME` VARCHAR(50) NOT NULL COMMENT '评论者昵称',
    `EMAIL` VARCHAR(100) DEFAULT NULL COMMENT '评论者邮箱',
    `WEBSITE` VARCHAR(255) DEFAULT NULL COMMENT '评论者网站',
    `CONTENT` VARCHAR(1000) NOT NULL COMMENT '评论内容',
    `STATUS` VARCHAR(20) DEFAULT 'PENDING' COMMENT '状态 (PENDING-待审核, APPROVED-已通过, REJECTED-已拒绝)',
    `IP_ADDRESS` VARCHAR(50) DEFAULT NULL COMMENT 'IP地址',
    `USER_AGENT` VARCHAR(500) DEFAULT NULL COMMENT '用户代理',
    `LIKE_COUNT` INT DEFAULT 0 COMMENT '点赞数',
    `EXT_JSON` TEXT DEFAULT NULL COMMENT '扩展信息JSON',
    `DELETE_FLAG` VARCHAR(255) DEFAULT 'NOT_DELETE' COMMENT '删除标志 (NOT_DELETE-未删除, DELETED-已删除)',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_TIME` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`ID`),
    INDEX `IDX_COMMENT_ARTICLE` (`ARTICLE_ID`),
    INDEX `IDX_COMMENT_PARENT` (`PARENT_ID`),
    INDEX `IDX_COMMENT_STATUS` (`STATUS`),
    INDEX `IDX_COMMENT_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='评论表';

-- ============================================================
-- 6. 媒体资源表 (BMS_MEDIA)
-- ============================================================
DROP TABLE IF EXISTS `BMS_MEDIA`;
CREATE TABLE `BMS_MEDIA` (
    `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
    `FILE_NAME` VARCHAR(255) NOT NULL COMMENT '文件名称',
    `ORIGINAL_NAME` VARCHAR(255) DEFAULT NULL COMMENT '原始文件名',
    `FILE_PATH` VARCHAR(500) NOT NULL COMMENT '文件路径',
    `FILE_URL` VARCHAR(500) DEFAULT NULL COMMENT '文件访问URL',
    `FILE_SIZE` BIGINT DEFAULT 0 COMMENT '文件大小(字节)',
    `FILE_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '文件类型 (IMAGE/VIDEO/AUDIO/DOCUMENT/OTHER)',
    `MIME_TYPE` VARCHAR(100) DEFAULT NULL COMMENT 'MIME类型',
    `FILE_EXT` VARCHAR(20) DEFAULT NULL COMMENT '文件扩展名',
    `THUMBNAIL_URL` VARCHAR(500) DEFAULT NULL COMMENT '缩略图URL',
    `WIDTH` INT DEFAULT NULL COMMENT '图片宽度',
    `HEIGHT` INT DEFAULT NULL COMMENT '图片高度',
    `DURATION` INT DEFAULT NULL COMMENT '音视频时长(秒)',
    `UPLOAD_USER` VARCHAR(32) DEFAULT NULL COMMENT '上传用户ID',
    `DOWNLOAD_COUNT` INT DEFAULT 0 COMMENT '下载次数',
    `STATUS` VARCHAR(20) DEFAULT 'ENABLE' COMMENT '状态 (ENABLE-启用, DISABLED-禁用)',
    `EXT_JSON` TEXT DEFAULT NULL COMMENT '扩展信息JSON',
    `DELETE_FLAG` VARCHAR(255) DEFAULT 'NOT_DELETE' COMMENT '删除标志 (NOT_DELETE-未删除, DELETED-已删除)',
    `CREATE_TIME` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `CREATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '创建人ID',
    `UPDATE_TIME` DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `UPDATE_USER` VARCHAR(32) DEFAULT NULL COMMENT '更新人ID',
    PRIMARY KEY (`ID`),
    INDEX `IDX_MEDIA_TYPE` (`FILE_TYPE`),
    INDEX `IDX_MEDIA_UPLOAD_USER` (`UPLOAD_USER`),
    INDEX `IDX_MEDIA_CREATE_TIME` (`CREATE_TIME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='媒体资源表';

-- ============================================================
-- 7. 初始化数据
-- ============================================================

-- 初始化文章分类
INSERT INTO `BMS_CATEGORY` (`ID`, `PARENT_ID`, `NAME`, `CODE`, `DESCRIPTION`, `SORT_CODE`, `STATUS`, `DELETE_FLAG`) VALUES
('1800000000000000001', '0', '技术分享', 'TECH', '技术相关文章', 1, 'ENABLE', 'NOT_DELETE'),
('1800000000000000002', '0', '生活随笔', 'LIFE', '生活感悟文章', 2, 'ENABLE', 'NOT_DELETE'),
('1800000000000000003', '0', '项目实战', 'PROJECT', '项目实战经验', 3, 'ENABLE', 'NOT_DELETE'),
('1800000000000000004', '0', '读书笔记', 'READING', '读书笔记分享', 4, 'ENABLE', 'NOT_DELETE');

-- 初始化文章标签
INSERT INTO `BMS_TAG` (`ID`, `NAME`, `CODE`, `COLOR`, `DESCRIPTION`, `SORT_CODE`, `STATUS`, `DELETE_FLAG`) VALUES
('1810000000000000001', 'Java', 'JAVA', '#f92672', 'Java编程语言', 1, 'ENABLE', 'NOT_DELETE'),
('1810000000000000002', 'Spring Boot', 'SPRING_BOOT', '#66d9ef', 'Spring Boot框架', 2, 'ENABLE', 'NOT_DELETE'),
('1810000000000000003', 'Vue', 'VUE', '#42b883', 'Vue.js框架', 3, 'ENABLE', 'NOT_DELETE'),
('1810000000000000004', 'Docker', 'DOCKER', '#2496ed', 'Docker容器技术', 4, 'ENABLE', 'NOT_DELETE'),
('1810000000000000005', 'MySQL', 'MYSQL', '#4479a1', 'MySQL数据库', 5, 'ENABLE', 'NOT_DELETE'),
('1810000000000000006', 'Redis', 'REDIS', '#dc382d', 'Redis缓存', 6, 'ENABLE', 'NOT_DELETE'),
('1810000000000000007', '微服务', 'MICROSERVICE', '#e6b450', '微服务架构', 7, 'ENABLE', 'NOT_DELETE'),
('1810000000000000008', '前端', 'FRONTEND', '#61dafb', '前端开发', 8, 'ENABLE', 'NOT_DELETE');

SET FOREIGN_KEY_CHECKS = 1;

-- ============================================================
-- 完成
-- ============================================================